apiVersion: v1
kind: Namespace
metadata:
  name: bank-a
  labels:
    demo: sovereign-inference
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
